Last-transcendence/ft_transcendence

src/service/nextjs/src/component/common/Header.tsx, src/service/nextjs/src/component/common/Layout.tsx, src/service/nextjs/src/component/main/body/chatting-room/icon.tsx, src/service/nextjs/src/component/main/body/chatting-room/index.tsx, src/service/nextjs/src/component/main/body/index.tsx, src/service/nextjs/src/component/main/footer/index.tsx, src/service/nextjs/src/style/main/body/chatting-room/index.module.css, src/service/nextjs/src/style/main/body/index.module.css, src/service/nextjs/src/style/main/footer/index.module.css
=> [Feat] [SCRUM-48] Main page 채팅 리스트 만들기 #5

src/service/nextjs/src/component/creatUser/bigAvatar.tsx, src/service/nextjs/src/component/creatUser/index.tsx, src/service/nextjs/src/component/creatUser/newButton.tsx, src/service/nextjs/src/component/creatUser/smallAvatar.tsx, src/service/nextjs/src/component/creatUser/userPhoto.tsx, src/service/nextjs/src/component/login/customButton.tsx, src/service/nextjs/src/component/login/index.tsx, src/service/nextjs/src/pages/creatUser/index.tsx, src/service/nextjs/src/pages/login/index.tsx, src/service/nextjs/src/style/creatUser/index.module.css, src/service/nextjs/src/style/login/index.module.css
=> [Feat] [SCRUM-37] 로그인 페이지 UI 구현 #9

src/service/nextjs/src/component/2fa/Message.tsx, src/service/nextjs/src/component/2fa/index.tsx, src/service/nextjs/src/component/2fa/lcokAvater.tsx, src/service/nextjs/src/pages/2fa/index.tsx, src/service/nextjs/src/style/2fa/index.module.css
=> [Feat] [SCRUM-63] 2차 인증 확인 페이지 UI구현 #12

src/service/nextjs/src/component/2fa/agree/agree2FABody.tsx, src/service/nextjs/src/component/2fa/agree/agree2FAButton.tsx, src/service/nextjs/src/component/2fa/agree/index.tsx, src/service/nextjs/src/pages/2fa/agree/index.tsx, src/service/nextjs/src/style/2fa/agree/index.module.css
=> [Feat] [SCRUM-61] 2차 인증 설정 문의 UI 구현 #14

src/service/nextjs/src/component/2fa/setting/checkCertification.tsx, src/service/nextjs/src/component/2fa/setting/emailInputBody.tsx, src/service/nextjs/src/component/2fa/setting/index.tsx, src/service/nextjs/src/pages/2fa/setting/index.tsx, src/service/nextjs/src/style/2fa/setting/index.module.css
=> [Feat] [SCRUM-62] 2차 인증 이메일 입력 페이지 UI 구현 #15

src/service/nextjs/src/component/common/hambergur-menu/icon.tsx, src/service/nextjs/src/component/common/hambergur-menu/index.tsx, src/service/nextjs/src/pages/test/index.tsx, src/service/nextjs/src/style/common/hambergur-menu/index.module.css
- Hambergur menu component 구현
- /test 경로에 component 테스트 페이지 구현해놨습니다 참고하셔서 사용법 및 결과 확인해주시면 되겠습니당
-
<br/>
=> [Feat] [SCRUM-67] 햄버거 메뉴 컴포넌트 구현 #24

src/service/nextjs/src/component/chat/ChatList.tsx, src/service/nextjs/src/component/chat/Message.tsx, src/service/nextjs/src/component/chat/NickMenu.tsx, src/service/nextjs/src/component/chat/SendChat.tsx, src/service/nextjs/src/component/chat/icon.tsx, src/service/nextjs/src/component/chat/index.tsx, src/service/nextjs/src/component/common/Header.tsx, src/service/nextjs/src/component/common/Layout.tsx, src/service/nextjs/src/component/common/hambergur-menu/index.tsx, src/service/nextjs/src/pages/chat/[id]/index.tsx, src/service/nextjs/src/pages/index.tsx
- 채팅방 구현
- 채팅 내용 추가
- 채팅 제출 인풋 추가
- 채팅 참여자 목록 추가
- 헤더 수정 (햄버거 메뉴 보이도록)
-
=> [Feat][SCRUM-34] 채팅방 구현 #28

src/service/nextjs/src/component/chat/create/submit/index.tsx, src/service/nextjs/src/component/common/ButtomButton.tsx, src/service/nextjs/src/component/main/body/index.tsx, src/service/nextjs/src/component/main/footer/index.tsx, src/service/nextjs/src/pages/chat/create/index.tsx, src/service/nextjs/src/pages/index.tsx, src/service/nextjs/src/style/chat/create/index.module.css, src/service/nextjs/src/style/common/buttom-button/index.module.css, src/service/nextjs/src/style/main/body/index.module.css, src/service/nextjs/src/style/main/index.module.css
- 공통 바텀 버튼 제작
- BottomButton과 ConfirmBottomButton이 추가되었습니다.
- 버튼을 아래에 놓기 위해서 height를 조정했습니다.
-
=> [Feat][SCRUM-72]common-bottom-button #30

src/service/nestjs/package.json, src/service/nestjs/src/util/swagger/swagger.ts, src/service/nestjs/yarn.lock, src/service/nextjs/src/style/common/hambergur-menu/index.module.css, src/service/nextjs/src/style/friend/add/index.module.css, src/service/nextjs/src/style/friend/index.module.css, src/service/nextjs/src/style/main/index.module.css
=> Fix/UI 깨짐 수정 #46

src/service/nextjs/src/component/profile/bottomAvatars.tsx, src/service/nextjs/src/component/profile/bottomProfile.tsx, src/service/nextjs/src/component/profile/index.tsx, src/service/nextjs/src/component/profile/newAvatar.tsx, src/service/nextjs/src/component/profile/newIcon.tsx, src/service/nextjs/src/component/profile/profileMenus.tsx, src/service/nextjs/src/component/profile/profileModar.tsx, src/service/nextjs/src/pages/profile/Profile.tsx, src/service/nextjs/src/pages/profile/testPrifile.tsx, src/service/nextjs/src/style/profile/profileModar.module.css
- 자신 이외의 유저 프로필 UI 구현
- 버튼 이벤트와 esc 이벤트는 추가해야함
=> [Feat] [SCRUM-81] 다른 사람 프로필 UI 구현 #33

src/service/nextjs/src/component/friend/add/index.tsx, src/service/nextjs/src/component/friend/list/index.tsx, src/service/nextjs/src/component/friend/list/status/index.tsx, src/service/nextjs/src/style/friend/add/index.module.css, src/service/nextjs/src/style/friend/index.module.css, src/service/nextjs/src/style/friend/list/index.module.css, src/service/nextjs/src/style/friend/list/status/index.module.css
- 친구목록 검색 화면을 제작했습니다
- 친구 목록 햄버거 메뉴 제작
- 친구 목록 검색 시 이벤트 핸들러 추가
- 친구 목록 검색에 친구 추가/삭제 버튼 추가
- 친구 추가 시 이벤트 핸들러 추가
- 친구 삭제 시 이벤트 핸들러 추가
-
=> [Feat][SCRUM-51] 친구목록 검색 제작 #41

src/service/nestjs/src/api/block/block.controller.ts, src/service/nestjs/src/api/block/dto/index.ts, src/service/nestjs/src/api/block/dto/request/index.ts, src/service/nestjs/src/api/friend/dto/index.ts, src/service/nestjs/src/api/friend/dto/request/index.ts, src/service/nestjs/src/api/friend/friend.controller.ts
=> [Fix] Dto import #65

src/service/nestjs/src/api/chatroom/chatroom.controller.ts, src/service/nestjs/src/api/chatroom/dto/index.ts, src/service/nestjs/src/api/chatroom/dto/request/index.ts
=> [Fix] Dto import #68

src/service/nestjs/src/api/friend/friend.controller.ts
=> [Fix] Dto import

src/service/nestjs/src/api/block/block.controller.ts, src/service/nestjs/src/api/friend/friend.controller.ts
- Block API swagger 연동
- 내용은 Swagger에서 확인하실 수 있습니다.
-
=> [Fix] Block API swagger 연동 #71

src/service/nestjs/src/api/channel/channel.controller.ts, src/service/nestjs/src/api/channel/channel.service.ts, src/service/nestjs/src/api/channel/dto/response/channel/index.ts, src/service/nestjs/src/api/channel/dto/response/index.ts
=> [Fix] [SCRUM-173] GET /channel password필드 제거 #98

src/service/nestjs/src/api/channel/decorator/is-valid-password.decorator.ts, src/service/nestjs/src/api/channel/dto/request/channel/index.ts
- GET /channel visibility, password 에러 메시지 수정
=> [Fix] [SCRUM-183] GET /channel visibility, password 에러 메시지 수정 #105

src/service/nextjs/src/component/chat/ChatList.tsx, src/service/nextjs/src/component/chat/NickMenu.tsx, src/service/nextjs/src/component/chat/index.tsx, src/service/nextjs/src/component/friend/add/index.tsx, src/service/nextjs/src/component/profile/modifyProfile/index.tsx, src/service/nextjs/src/hook/useFetchData.ts, src/service/nextjs/src/pages/chat/create/index.tsx
=> [HOTFIX] 빌드 에러 수정 (api.ts 함수 경로 수정)

src/service/nestjs/src/api/channel/channel.service.ts
- Build error 해결을 위한 class name 수정
- dto channel class name 수정
- build 확인 완료
=> [HOTFIX] class name

src/service/nestjs/src/api/ban/ban.controller.ts, src/service/nestjs/src/api/ban/ban.module.ts, src/service/nestjs/src/api/channel/channel.controller.ts, src/service/nestjs/src/api/channel/channel.module.ts, src/service/nestjs/src/api/participant/participant.controller.ts, src/service/nestjs/src/api/participant/participant.module.ts
- Circular dependency error 수정했습니다
-
-
=> [Debug] Circular dependency #133

src/service/nextjs/src/component/chat/ChatRoomLayout.tsx, src/service/nextjs/src/component/chat/Message.tsx, src/service/nextjs/src/component/chat/ParticipantList.tsx, src/service/nextjs/src/component/common/detailProfile/openProfileAvatar.tsx, src/service/nextjs/src/component/common/user/bried-information/index.tsx, src/service/nextjs/src/component/friend/add/index.tsx, src/service/nextjs/src/component/friend/index.tsx, src/service/nextjs/src/component/friend/list/index.tsx, src/service/nextjs/src/component/main/body/index.tsx, src/service/nextjs/src/hook/useFetchData.ts, src/service/nextjs/src/pages/profile/testOtherUserProfile/index.tsx
- DM방과 채팅방의 컴포넌트 분리
- DM방의 참여목록 추가, 어드민 기능 제거
- 채널설정 컴포넌트 분리 (채널생성과 수정이 같은 컴포넌트 쓰도록)
---
죄송합니다. 작업하다보니 pr 올라가있는 브랜치에 커밋을 날리고 있었네요.. #117의 내용도 같이 올라갔습니다.
https://github.com/Last-transcendence/ft_transcendence/issues/117
- 친구 추가 시 친구인지 확인하기
- 프로필 클릭시 프로필 조회
=> [Feat] [SCRUM-181] dm방 기능 개선 #102

src/service/nestjs/src/api/auth/auth.controller.ts, src/service/nextjs/src/context/socket.context.tsx
=> [Fix] Socket context #148

src/service/nextjs/src/component/common/Header.tsx, src/service/nextjs/src/component/common/creatOrModifyBody/creatOrModifyBody.tsx, src/service/nextjs/src/component/common/detailProfile/bottomProfile.tsx, src/service/nextjs/src/component/common/detailProfile/openProfileAvatar.tsx, src/service/nextjs/src/component/game/scene/index.ts, src/service/nextjs/src/component/game/scene/main/index.ts, src/service/nextjs/src/component/main/body/index.tsx, src/service/nextjs/src/component/main/matching-button/index.tsx, src/service/nextjs/src/component/profile/modifyProfile/index.tsx, src/service/nextjs/src/context/socket.context.tsx, src/service/nextjs/src/pages/game/index.tsx
=> [Feat] [SCRUM-202] Game page API 연결 #152

src/service/nestjs/src/common/auth/guard/index.ts, src/service/nestjs/src/common/auth/guard/user-jwt-auth.guard-ws.ts
close #151
- gateway에서 쓸 guard 데코레이터 구현
=> [Feat] [SCRUM-196] gateway에서 쓸 guard 데코레이터 구현 #151

src/service/nestjs/src/api/channel/channel.gateway.ts, src/service/nestjs/src/api/participant/participant.controller.ts
- gateway channel join 구현
- gateway channel join 구현
- POST participant 제거
=> [Feat] [SCRUM-203] gateway channel join 구현 #159

src/service/nestjs/src/api/channel/channel.controller.ts, src/service/nestjs/src/api/channel/channel.gateway.ts, src/service/nestjs/src/api/channel/channel.service.ts
- gateway channel edit 구현
- gateway channel edit 구현
- controller PATCH channel 삭제
=> [Feat] [SCRUM-209] gateway channel edit 구현 #168

src/service/nestjs/Dockerfile, src/service/nestjs/src/api/auth/auth.controller.ts, src/service/nestjs/src/api/friend/friend.controller.ts, src/service/nestjs/src/api/game/game.gateway.ts, src/service/nextjs/src/component/game/scene/main/index.ts, src/service/nextjs/src/pages/game/[id].tsx
=> [Feat] [SCRUM-204] Game socket gateway 구현 #160

src/service/nextjs/src/component/friend/list/status/index.tsx
=> [HOTFIX] 빌드 에러 수정

src/service/nestjs/src/api/friend/dto/index.ts, src/service/nestjs/src/api/friend/dto/response/get/index.ts, src/service/nestjs/src/api/friend/dto/response/index.ts, src/service/nestjs/src/api/friend/friend.controller.ts, src/service/nestjs/src/api/friend/friend.service.ts
=> [Debug] Prisma include 오류 수정 #183

src/service/nestjs/src/api/chatroom/chatroom.controller.ts
=> [Debug] [SCRUM-226] GET /chatroom #192

src/service/nestjs/src/api/channel/channel.module.ts
=> [HOTFIX] 모듈 중복 제거

src/service/nestjs/src/api/channel/channel.gateway.ts, src/service/nestjs/src/api/channel/channel.service.ts
close #196
- gateway channel join 반환 값 수정
- gateway channel join 반환 값 수정
=> [Fix] [SCRUM-228] gateway channel join 반환 값 수정 #196

src/service/nestjs/src/api/api.module.ts, src/service/nestjs/src/api/test/test.controller.ts, src/service/nestjs/src/api/test/test.module.ts, src/service/nestjs/src/api/test/test.service.ts
close #198
- 테스트용 전체 Channel, User 삭제 API 추가
- 테스트용 전체 Channel, User 삭제 API 추가
=> [Feat] [SCRUM-231] 테스트용 전체 Channel, User 삭제 API 추가 #198

src/service/nestjs/src/api/channel/channel.gateway.ts, src/service/nestjs/src/api/channel/channel.module.ts, src/service/nestjs/src/api/channel/channel.service.ts
- gateway channel message 구현
- gateway channel message 구현
=> Feat/scrum 232/gateway channel message 구현 #200

src/service/nestjs/src/api/auth/auth.controller.ts, src/service/nestjs/src/api/auth/auth.module.ts, src/service/nestjs/src/api/auth/dto/request/register/index.ts, src/service/nestjs/src/api/auth/service/auth.service.ts, src/service/nestjs/src/api/auth/service/twofactor.service.ts, src/service/nestjs/src/api/user/dto/request/create/index.ts, src/service/nestjs/src/api/user/user.controller.ts, src/service/nestjs/src/api/user/user.service.ts
- Updatedto 수정 및 회원가입 파일업로드 기능 추가
- Updatedto 2fa bool타입에서 string타입으로 변경했습니다.
- logout clearCookie 오류기능 수정했습니다.
- 회원가입에  파일업로드 기능 추가했습니다.
-
=> [Feat] [SCRUM-223]  Updatedto 수정 및 회원가입 파일업로드 기능 추가 #182

src/service/nestjs/src/api/auth/auth.controller.ts, src/service/nestjs/src/api/channel/channel.module.ts, src/service/nestjs/src/api/mute/mute.module.ts
- user_status 소문자 이슈, muteservice 의존성 문제
- online를 소문자로 처리를 했습니다. 대문자로 수정했습니다.
- muteservice 의존성문제 수정했습니다.
-
=> [Bug] user_status 소문자 이슈, muteservice 의존성 문제

src/service/nextjs/src/component/auth/login/index.tsx, src/service/nextjs/src/style/auth/login/index.module.css
=> [Feat] [SCRUM-211] LoginPage Link 변경 #174

src/service/nestjs/src/api/auth/auth.controller.ts, src/service/nestjs/src/api/auth/service/auth.service.ts, src/service/nestjs/src/main.ts, src/service/nextjs/next.config.js, src/service/nextjs/src/component/auth/login/index.tsx, src/service/nextjs/src/component/common/creatOrModifyBody/creatOrModifyBody.tsx, src/service/nextjs/src/component/common/creatOrModifyBody/userPhoto.tsx, src/service/nextjs/src/component/profile/common/myImage.tsx, src/service/nextjs/src/component/profile/common/newAvatar.tsx, src/service/nextjs/src/component/profile/myProfile/index.tsx, src/service/nextjs/src/pages/auth/login/callback/index.tsx, src/service/nextjs/src/style/common/creatOrModify/index.module.css
- creatOrModify 그리고 myProfile에 백에 저장한 img 호출
- 이미지 업로드 가능하게 변경했습니다.
- 2fa관련 코드 추가로 커밋할 겁니다.
- 회원가입 시 넘어오는 커리(nickname) 받게 해놨습니다.
- 프로그램 진행 중 백 코드 일부 오류로 인해 문제 발생하여 일부 수정하였습니다.
=> [Feat] [SCRUM-234] creatOrModify 그리고 myProfile에 백에 저장한 img 호출 #204

src/service/nextjs/src/component/profile/myProfile/index.tsx, src/service/nextjs/src/component/profile/myProfile/myProfileBodys.tsx, src/service/nextjs/src/component/profile/myProfile/myProfileMenu.tsx, src/service/nextjs/src/style/profile/myProfile/index.module.css
- loginOut API 연결
- 현재 회원가입 페이지 수정 중으로 테스트 시 스웨거로 회원가입 후 진행해 주세요.
- swagger로 회원가입 후 myProfile에서 로그아웃 누르면 정상작동되는거 확인했습니다.
=> [Feat] [SCRUM-212] loginOut API 연결 #175

src/service/nestjs/src/api/channel/channel.gateway.ts
close #231
- gateway channel message authGuard 추가
- gateway channel message authGuard 추가
-
=> [Fix] [SCRUM-248] gateway channel message authGuard 추가 #231

src/service/nestjs/src/api/chat/chat.controller.ts, src/service/nestjs/src/api/chat/dto/request/create/index.ts, src/service/nestjs/src/api/chat/dto/request/index.ts, src/service/nestjs/src/api/chatroom/chatroom.gateway.ts, src/service/nestjs/src/api/chatroom/chatroom.service.ts
- getChat error수정, socket수정
- await부분이 없어서 상대방 chat이 생성이 되지않아서 생긴 이슈입니다.
- Socket부분을 삭제해야 동작을 해서 수정했습니다.
- Create로 할경우 gameDto가 적용이 되어 스웨거 편의성으로 인해CreateChat으로수정했습니다.
-
close #225
=> [Fix] [SCRUM-238] getChat부분 수정및 socket error 수정 #225

src/service/nestjs/src/api/channel/channel.gateway.ts
- 유저가 채널에 들어올 시 채널 안에 있는 유저들에게 입장 알리는 코드 추가
- 유저가 채널에 들어올 시 채널 안에 있는 유저들에게 입장 알리는 코드 추가
- 에러 시 응답에 message 추가
=> [Fix] [SCRUM-233] gateway channel join emit 코드 추가 #217

src/service/nestjs/src/api/user/user.controller.ts
- image delete 
- 이미지 변경시 전이미지 삭제
-
=> [Feat] [SCRUM-242] image delete #222

src/service/nestjs/src/api/channel/channel.gateway.ts, src/service/nestjs/src/api/participant/participant.controller.ts, src/service/nestjs/src/api/participant/participant.service.ts
close #219
- gateway channel role 구현
- gateway channel role 구현
- participant controller Patch(':id') 제거
-
=> [Feat] [SCRUM-239] gateway channel role 구현 #219

src/service/nestjs/src/api/channel/channel.gateway.ts, src/service/nestjs/src/api/channel/channel.module.ts
- merge conflict 해결
- merge conflict 해결
-
=> [Refactor] merge conflict 해결

src/service/nextjs/src/component/chat/AdminNickMenu.tsx, src/service/nextjs/src/component/chat/ChatRoomLayout.tsx, src/service/nextjs/src/component/chat/CommonChatRoomPage.tsx, src/service/nextjs/src/component/chat/Message.tsx, src/service/nextjs/src/component/chat/ParticipantList.tsx, src/service/nextjs/src/component/chat/PrivateChatRoomPage.tsx, src/service/nextjs/src/component/chat/PrivateParticipantList.tsx, src/service/nextjs/src/component/chat/create/password/index.tsx, src/service/nextjs/src/component/chat/create/title/index.tsx, src/service/nextjs/src/component/common/ChannelSetting.tsx, src/service/nextjs/src/component/common/CustomModal.tsx, src/service/nextjs/src/component/common/detailProfile/bottomProfile.tsx, src/service/nextjs/src/component/common/detailProfile/openProfileAvatar.tsx, src/service/nextjs/src/component/friend/list/index.tsx, src/service/nextjs/src/component/main/body/index.tsx, src/service/nextjs/src/context/index.tsx, src/service/nextjs/src/context/listen.context.tsx, src/service/nextjs/src/context/socket.context.tsx, src/service/nextjs/src/service/getFriend.ts, src/service/nextjs/src/type/friend.type.ts
- dm(chatroom) 페이지 api 연동 
- 소켓 연결이 안되어서 작동을 확인해보지 못했습니다. 주석 친 부분은 테스트 후 다시 해제하겠습니다.
- chatroom 작업하면서 channel도 같이 테스트했기 때문에, channel 부분도 같이 수정되었습니다.
- listen context은 chatroom 을 위한 context입니다.
=> [Feat][SCRUM-155] dm(chatroom) 페이지 api 연동 #191

src/service/nestjs/prisma/migrations/20240122131145_init/migration.sql, src/service/nestjs/prisma/schema.prisma, src/service/nestjs/src/api/channel/channel.gateway.ts, src/service/nestjs/src/api/game/game.gateway.ts, src/service/nestjs/src/api/game/game.service.ts, src/service/nestjs/src/api/participant/dto/request/create/index.ts, src/service/nestjs/src/api/participant/participant.service.ts, src/service/nestjs/src/common/model/participant.model.ts
=> [Feat] [SCRUM-256] Channel invite 구현 #243

src/service/nestjs/src/api/game/game.gateway.ts, src/service/nestjs/src/api/game/game.service.ts, src/service/nextjs/src/component/game/scene/main/index.ts
=> [Feat] [SCRUM-257] Game 상대방 연결 끊겼을 때 처리 #245

src/service/nestjs/prisma/schema.prisma, src/service/nestjs/src/api/channel/channel.gateway.ts
- gateway channel message room 문제 수정
- scheme.prisma participant channelId @unique 제거
=> [Fix] [SCRUM-251] gateway channel message room 문제 수정 #236

src/service/nestjs/src/api/chatroom/chatroom.service.ts
=> [Feat] [SCRUM-252] socket module error #237

src/service/nestjs/prisma/migrations/20240123071406_init/migration.sql
- migration 파일 추가
- migration 파일 추가
-
=> [HOTFIX] migration 파일 추가

src/service/nestjs/src/api/chatroom/chatroom.gateway.ts
- message 보낼때 srcnickname도 보내게 수정
-
-
clase #249
=> [Feat] [SCRUM-260] message srcnickname return #249

src/service/nestjs/prisma/migrations/20240123071406_init/migration.sql, src/service/nestjs/src/api/channel/channel.gateway.ts, src/service/nestjs/src/api/participant/participant.service.ts
- gateway channel mute 구현
- gateway channel mute 구현
- 불필요한 console.log 삭제
-
=> [Feat] [SCRUM-244] gateway channel mute 구현 #227

src/service/nestjs/src/api/chatroom/chatroom.gateway.ts
- blockuser에 없을경우 에러로 빠지게 처리를 해서 수정했습니다.
-
-
=> [Feat] [SCRUM-262] chat_user #254

src/service/nestjs/src/api/channel/channel.gateway.ts
- gateway channel kick, ban 구현
- #228
- #229
-
=> [Feat] [SCRUM-245] gateway channel kick 구현 [SCRUM-246] gateway channel ban 구현

src/service/nestjs/src/api/channel/channel.gateway.ts, src/service/nestjs/src/api/channel/channel.service.ts
close #259
- gateway channel join 예외처리 안된 것 처리
- DB 조작 명령에 들어가는 키, 값 수정
- participant 삭제 시 socket.leave 적용
-
=> [Fix] [SCRUM-258] gateway channel join 예외처리 안된 것 처리

src/service/nextjs/src/component/common/accessControl/IsWithAuth.tsx, src/service/nextjs/src/component/common/accessControl/IsWithNotAuth.tsx, src/service/nextjs/src/pages/auth/login/index.tsx, src/service/nextjs/src/pages/auth/register/index.tsx, src/service/nextjs/src/pages/index.tsx, src/service/nextjs/src/pages/profile/modifyProfile/index.tsx, src/service/nextjs/src/pages/profile/myProfile/index.tsx
- auth 상황에 따라 페이지 이동 제한 기능 추가
- 로그인 시 auth 접근 불가
- 로그아웃 시 auth 페이지 외 접근 불가
- 2fa 접근은 2개 다 해당되어 따로 처리하지 못함, 고민해야할 사항
=> [Feat] [SCRUM-269] auth 상황에 따라 페이지 이동 제한 기능 추가 #265

src/service/nestjs/src/api/channel/channel.gateway.ts, src/service/nestjs/src/api/channel/channel.service.ts
- gateway channel message return 비어있는 값 문제 해결
- 비동기 함수에 await 붙여서 string 받도록 수정
- gateway channel emit info 반환 값에 role, nickname 추가
-
=> Feat/scrum 267/gateway channel message return 값이 비어있음 #264

src/service/nestjs/src/api/channel/channel.gateway.ts, src/service/nestjs/src/api/channel/channel.service.ts
…삭제 건너뛰도록 수정
close #269
- channel join 들어가는 방과 기존 방이 같으면 participant 삭제 건너뛰도록 수정
- 권한 유지 목적. #269 
-
=> [Fix] [SCRUM-270] gateway channel join 들어가는 방과 기존 방이 같으면 participant 삭제 건너뛰도록 수정 #269

src/service/nestjs/src/api/auth/auth.controller.ts
- logout시 ftjwt를 사용해서 유저정보가 달라 error가 발생했습니다.
-
-
=> [Fix] [SCRUM-271] logout시 error 수정 #271

src/service/nextjs/src/component/chat/AdminNickMenu.tsx, src/service/nextjs/src/component/chat/ChatRoomLayout.tsx, src/service/nextjs/src/component/chat/CommonChatRoomPage.tsx, src/service/nextjs/src/component/chat/Message.tsx, src/service/nextjs/src/component/chat/NickMenu.tsx, src/service/nextjs/src/component/chat/ParticipantList.tsx, src/service/nextjs/src/component/chat/PrivateChatRoomPage.tsx, src/service/nextjs/src/component/common/Header.tsx, src/service/nextjs/src/component/common/detailProfile/openProfileAvatar.tsx, src/service/nextjs/src/component/friend/add/index.tsx
- chatroom/channel-오류-수정
- chatroom/channel-오류-수정
=> [Feat] [SCRUM-272] chatroom/channel-오류-수정 #274

src/service/nestjs/src/api/channel/channel.gateway.ts, src/service/nestjs/src/api/channel/channel.service.ts
- gateway channel mute, kick, ban 권한 로직 수정
- #276 
- [[Fix] gateway channel leave 함수 에러](https://github.com/Last-transcendence/ft_transcendence/commit/3bf5f64ee42ac50b3bea86b03904ffad24f7af9a)
-
=> [Fix] [SCRUM-274] gateway channel mute, kick, ban 권한 로직 수정 #276

src/service/nestjs/src/api/channel/channel.gateway.ts, src/service/nestjs/src/api/participant/participant.service.ts
- gateway channel ban kick mute 에러 수정
- gateway channel ban kick mute 에러 수정
-
=> [Fix] [SCRUM-281] gateway channel ban kick mute 에러 수정 #287

src/service/nestjs/src/api/game/dto/request/connected/index.ts, src/service/nestjs/src/api/game/dto/request/index.ts, src/service/nestjs/src/api/game/game.gateway.ts, src/service/nestjs/src/api/game/game.service.ts, src/service/nextjs/src/component/game/scene/disconnected/index.ts, src/service/nextjs/src/component/game/scene/index.ts, src/service/nextjs/src/component/game/scene/main/index.ts, src/service/nextjs/src/component/game/scene/result/index.ts, src/service/nextjs/src/pages/game/index.tsx
=> [Feat] [SCRUM-257] Game handle disconnect #290

src/service/nestjs/src/api/channel/channel.gateway.ts, src/service/nestjs/src/api/participant/dto/request/update/index.ts, src/service/nestjs/src/api/participant/participant.service.ts
- gateway channel join 들어갔다 뒤로가기 후 다시 들어갈 때 실패 문제 해결
- #282 
-
=> [Fix] [SCRUM-277] gateway channel join 들어갔다 뒤로가기 후 다시 들어갈 때 실패 문제 해결 #282

src/service/nestjs/src/api/chatroom/chatroom.gateway.ts, src/service/nestjs/src/api/invite/dto/index.ts, src/service/nestjs/src/api/invite/dto/request/index.ts, src/service/nestjs/src/api/invite/dto/request/invite/index.ts, src/service/nestjs/src/api/invite/invite.gateway.ts, src/service/nestjs/src/api/invite/invite.module.ts
- 프라이빗초대소켓 기능 추가
- 로그인시 전체 연결을 합니다.
- 초대를 보낼때 invite message를 보냅니다.
-
=> [Feat] [SCRUM-278] channel private invite #283

src/service/nestjs/.gitignore, src/service/nestjs/src/api/ban/ban.service.ts
=> [Feat] [SCRUM-263] Channel socket join에서 ban 당한 user 확인하는 로직 추가 #298

src/service/nestjs/src/api/channel/channel.gateway.ts, src/service/nestjs/src/api/mute/mute.service.ts, src/service/nestjs/src/api/participant/participant.service.ts
=> [Feat] [SCRUM-264] Channel gateway message에서 일정 시간 후 mute 해제 로직 추가 #300

src/service/nestjs/src/api/api.module.ts, src/service/nestjs/src/api/block/block.module.ts, src/service/nestjs/src/api/channel/channel.service.ts, src/service/nestjs/src/api/chatroom/chatroom.module.ts, src/service/nestjs/src/api/invite/invite.module.ts
=> [Feat] [SCRUM-291] invite error 수정 #304

src/service/nextjs/src/component/chat/AdminNickMenu.tsx, src/service/nextjs/src/component/chat/ChatRoomLayout.tsx, src/service/nextjs/src/component/chat/CommonChatRoomPage.tsx, src/service/nextjs/src/component/chat/Message.tsx, src/service/nextjs/src/component/chat/NickMenu.tsx, src/service/nextjs/src/component/chat/ParticipantList.tsx, src/service/nextjs/src/component/common/CustomConfirmModal.tsx, src/service/nextjs/src/component/common/CustomModal.tsx, src/service/nextjs/src/component/common/Header.tsx, src/service/nextjs/src/component/main/matching-button/icon.tsx, src/service/nextjs/src/context/listen.context.tsx, src/service/nextjs/src/pages/_app.tsx, src/service/nextjs/src/style/common/custom-modal/index.module.css, src/service/nextjs/src/style/theme.ts, src/service/nextjs/src/type/channel.type.ts
- 어드민 기능 개선
- 어드민 기능 개선
- 스크롤 내려가는 기능 추가
- 색상 수정
=> [Feat][SCRUM-289] 어드민 기능 개선 #294

src/service/nestjs/src/api/invite/invite.gateway.ts
- invite 타입 수정
- destnickname가 아닌 srcname으로 수정했습니다.
-
close #311
=> [fix] [SCRUM-293] invite 타입 수정 #311

src/service/nestjs/src/api/channel/channel.gateway.ts, src/service/nestjs/src/api/participant/participant.service.ts
=> [Fix] SCRUM-286 admin change 불가 #318

src/service/nestjs/src/api/ban/ban.service.ts, src/service/nestjs/src/api/channel/channel.gateway.ts, src/service/nestjs/src/api/channel/channel.service.ts
- ban문제 해결 #319
- [Fix] [SCRUM-296](https://younganswer.atlassian.net/browse/SCRUM-296?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ) ban 당한 유저가 다시 방에 들어가짐
- [Fix] [SCRUM-297](https://younganswer.atlassian.net/browse/SCRUM-297?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ) owner가 같은 유저 두 번 ban 하면 에러 발생
- [[Fix] info 에 profileImageURI 추가](https://github.com/Last-transcendence/ft_transcendence/commit/195dee49c0b6ec49366bf3cb2f8077e23a913d90)
-
[SCRUM-296]: https://younganswer.atlassian.net/browse/SCRUM-296?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SCRUM-297]: https://younganswer.atlassian.net/browse/SCRUM-297?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3 …
=> [Fix] [SCRUM-294] ban문제 해결 #319

src/service/nextjs/src/component/chat/AdminNickMenu.tsx, src/service/nextjs/src/component/chat/ChatRoomLayout.tsx, src/service/nextjs/src/component/chat/CommonChatRoomPage.tsx, src/service/nextjs/src/component/chat/Message.tsx, src/service/nextjs/src/component/chat/ParticipantList.tsx, src/service/nextjs/src/component/chat/create/title/index.tsx, src/service/nextjs/src/component/common/ChannelSetting.tsx, src/service/nextjs/src/component/main/body/index.tsx, src/service/nextjs/src/type/channel.type.ts
=> [Feat][SCRUM-299]채널 기능 개선#325

src/service/nestjs/src/api/channel/channel.gateway.ts
- leave emit을 하면 message가 이상하게 들어옴
- 메시지, 이미지uri를 보내지않고 채널id, 유저id, 유저닉네임을 보내게 수정했습니다.
-
=> [Feat] [SCURM-285] leave emit을 하면 message가 이상하게 들어옴 #323

src/service/nestjs/src/api/channel/channel.gateway.ts, src/service/nestjs/src/api/channel/channel.service.ts
close #297
- gateway channel participant 0이면 채널 삭제
- #297 
-
=> [Feat] [SCRUM-275] gateway channel participant 0이면 채널 삭제

src/service/nestjs/src/api/channel/channel.gateway.ts, src/service/nestjs/src/api/channel/channel.service.ts
=> [fix] [SCRUM-303] role false 수정 #329

src/service/nextjs/src/component/profile/myProfile/fightRecord.tsx, src/service/nextjs/src/component/profile/myProfile/myProfileBodys.tsx
=> [Feat] [SCRUM-292] 게임 전적 스타일 변경 #308

src/service/nestjs/src/api/channel/channel.gateway.ts, src/service/nestjs/src/api/participant/participant.service.ts
- join 두번 보내면 입장 안됨 (뒤로갔다가 같은 채널 다시 들어가면 실패)
- 전달하는 매개변수 수정
-
=> [Fix] [SCRUM-302] join 두번 보내면 입장 안됨 (뒤로갔다가 같은 채널 다시 들어가면 실패) #336

src/service/nestjs/src/api/participant/participant.service.ts
=> [HOTFIX] build error

src/service/nestjs/src/api/channel/channel.service.ts
=> [Fix] [SCRUM-311] 비어있는 채널 자동 삭제 #346

src/service/nestjs/src/api/game/game.gateway.ts, src/service/nestjs/src/api/game/game.service.ts
=> [Debug] Game gateway error 수정 #349

src/service/nextjs/src/component/game/scene/result/index.ts, src/service/nextjs/src/context/game.context.tsx, src/service/nextjs/src/pages/game/callback/index.tsx
=> [Fix] Game result scene에서 history context update 요청 #342

src/service/nestjs/prisma/schema.prisma
=> [Fix] DB schema cascade option 추가 #353

src/service/nextjs/src/component/common/detailProfile/BottomAvatars.tsx, src/service/nextjs/src/component/common/detailProfile/ProfilePageBody.tsx, src/service/nextjs/src/component/profile/myProfile/Odds.tsx, src/service/nextjs/src/style/common/detailProfile/index.module.css
- 다른 유저 프로필 하단 아이콘 위치조정, 게임전적 소수점 없애기 
- 다른 유저 프로필 하단 아이콘 위치조정
- 게임전적 소수점 없애기
=> [Feat] [SCRUM-306] 다른 유저 프로필 하단 아이콘 위치조정, 게임전적 소수점 없애기 #338

src/service/nextjs/src/component/common/creatOrModifyBody/CreatOrModifyBody.tsx
- 회원가입 401 에러 문제 해결
- 401에러 발생 시 로그인 페이지로 보냄
=> [Feat] [SCRUM-309] 회원가입 401 에러 문제 해결 #343

src/service/nextjs/src/component/common/detailProfile/BottomProfile.tsx, src/service/nextjs/src/component/friend/add/index.tsx, src/service/nextjs/src/style/friend/add/index.module.css
-  otherUserProfile에서 게임 아바타 제거 
-  otherUserProfile에서 게임 아바타 제거(이제는 DM과 친구  추가만 남아있음)
-  유저 차단 메세지 css 적용
=> [Feat] [SCRUM-313] otherUserProfile에서 게임 아바타 제거 #351

src/service/nestjs/prisma/migrations/20240126074641_init/migration.sql, src/service/nestjs/src/api/ban/ban.controller.ts, src/service/nestjs/src/api/channel/channel.gateway.ts, src/service/nestjs/src/api/channel/channel.service.ts, src/service/nestjs/src/api/participant/dto/request/update/index.ts, src/service/nestjs/src/api/participant/dto/response/participant/index.ts, src/service/nestjs/src/api/participant/participant.service.ts
=> [Debug] Channel gateway #358

src/service/nestjs/src/api/user/user.controller.ts, src/service/nestjs/src/api/user/user.service.ts
=> [Feat] User API online offline #360

src/service/nestjs/src/api/block/block.controller.ts, src/service/nestjs/src/api/block/block.service.ts, src/service/nestjs/src/api/chat/chat.service.ts, src/service/nestjs/src/api/chatroom/chatroom.gateway.ts, src/service/nestjs/src/api/chatroom/chatroom.service.ts
-블락처리시 챗룸딜리트문제
- 블락유저 처리시 챗룸 삭제에 문제가있어 수정했습니다.
- 블락유저딜리트기능 추가했습니다.
- 챗룸 첫 생성에 문제가 있어 수정했습니다.
-
=> [Feat] [SCRUM-312] 블락처리시 챗룸딜리트문제 #350

src/service/nestjs/src/api/channel/channel.gateway.ts
close #366 
- role false, 권한 유지되는 문제
-
-
=> [Fix] [SCRUM-320] role false, 권한 유지되는 문제 #366

src/service/nestjs/src/api/channel/channel.gateway.ts, src/service/nestjs/src/api/channel/channel.service.ts
- delete channel 시 존재하지 않는 채널 삭제 에러 해결
- 삭제 전 채널 존재확인
-
=> [Hotfix] delete channel

src/service/nestjs/src/api/block/block.service.ts, src/service/nestjs/src/api/chatroom/chatroom.gateway.ts, src/service/nestjs/src/api/invite/invite.gateway.ts
=> [Feat] [SCRUM-319] block user data날리기 #365

src/service/nestjs/src/api/channel/channel.gateway.ts
- join check, role socketId
- 
-
=> [HOTFIX] join check, role socketId

src/service/nextjs/src/component/common/accessControl/IsWithAuth.tsx, src/service/nextjs/src/component/common/accessControl/IsWithNotAuth.tsx, src/service/nextjs/src/component/common/monitorLogout/index.tsx, src/service/nextjs/src/context/auth.context.tsx, src/service/nextjs/src/pages/_app.tsx, src/service/nextjs/src/pages/auth/login/callback/index.tsx
=> [Feat] [SCRUM-279] 정상 종료 외 종료에 대한 로그아웃 처리 #285

src/service/nestjs/src/api/auth/auth.controller.ts, src/service/nestjs/src/api/auth/service/auth.service.ts, src/service/nestjs/src/api/user/user.service.ts
=> [Feat] [SCRUM-318] nick name 400 #363

src/service/nestjs/prisma/migrations/20240126132445_init/migration.sql, src/service/nestjs/prisma/schema.prisma, src/service/nestjs/src/api/channel/channel.gateway.ts, src/service/nestjs/src/api/mute/mute.controller.ts, src/service/nestjs/src/api/mute/mute.service.ts
=> [Fix] Mute scheme 

src/service/nextjs/src/component/common/creatOrModifyBody/CreatOrModifyBody.tsx, src/service/nextjs/src/component/common/monitorLogout/index.tsx, src/service/nextjs/src/component/profile/myProfile/FightRecords.tsx, src/service/nextjs/src/component/profile/myProfile/MyProfileBody.tsx, src/service/nextjs/src/component/profile/myProfile/MyProfileMenu.tsx, src/service/nextjs/src/component/profile/myProfile/Odds.tsx
=> 로그인 로그아웃 시 발생하는 에러 처리

src/docker-compose.yml
=> [Fix] docker-compose.yml

src/service/nestjs/src/api/channel/channel.gateway.ts
=> [HOTFIX] deleteEmptyChannel 삭제

src/service/nestjs/src/main.ts
=> [Debug] backend public GET 수정 #383

src/service/nestjs/src/api/channel/channel.gateway.ts
=> [Fix] admin시 자신에게 알람안오는 버그 수정

src/service/nextjs/src/component/common/Header.tsx, src/service/nextjs/src/component/common/accessControl/IsWithAuth.tsx, src/service/nextjs/src/component/common/accessControl/IsWithNotAuth.tsx, src/service/nextjs/src/component/common/creatOrModifyBody/CreatOrModifyBody.tsx, src/service/nextjs/src/component/profile/myProfile/MyProfileBody.tsx, src/service/nextjs/src/component/profile/myProfile/TwoFACheck.tsx, src/service/nextjs/src/style/profile/myProfile/index.module.css
유저 수정 페이지 에러 메세지 개선
- 바탕화면 아바타에 유저 이미지 추가, 게임 페이지 글자 겹침 해결
- 바탕화면 아바타에 유저 이미지 추가
-  게임 페이지 글자 겹침 해결
- 유저 수정페이지 에러 개선
=> 바탕화면 아바타에 유저 이미지 추가, 게임 페이지 글자 겹침 해결

src/service/nestjs/src/api/channel/channel.gateway.ts
=> [Fix] null nickname

src/service/nextjs/src/component/common/creatOrModifyBody/CreatOrModifyBody.tsx
=> [Fix] 라우터 푸쉬중 에러처리

src/service/nextjs/src/component/common/creatOrModifyBody/CreatOrModifyBody.tsx
- 에러 뒤에 return 처리
- 에러 발생 후 뒤에 코드마저 작동되어서 return처리함
=> 에러 뒤에 return ; 처리 추가. (에러 발생후에도 뒤에 코드 실행되는 문제가 있었음)

src/service/nestjs/prisma/migrations/20240126204228_init/migration.sql, src/service/nestjs/prisma/schema.prisma, src/service/nestjs/src/api/channel/channel.gateway.ts, src/service/nestjs/src/api/game/dto/request/create/index.ts, src/service/nestjs/src/api/game/game.gateway.ts, src/service/nestjs/src/api/game/game.service.ts, src/service/nextjs/src/component/chat/CommonChatRoomPage.tsx, src/service/nextjs/src/component/game/scene/main/index.ts, src/service/nextjs/src/component/game/scene/queue/index.ts
=> [Fix] Game invite

src/service/nestjs/src/api/auth/auth.controller.ts
- 2fa 설정이 되어 있는데 바로 토큰이 발급되는 문제 해결
-
-
=> [fix] Auth login token

src/service/nestjs/src/api/game/game.gateway.ts, src/service/nestjs/src/api/game/game.service.ts
=> [Debug] Game

src/service/nestjs/src/api/channel/channel.gateway.ts, src/service/nestjs/src/api/channel/channel.service.ts
- channel create 시 빈 채널 삭제되지 않던 문제 해결
- [[HOTFIX] channel create 시 빈 채널 삭제](https://github.com/Last-transcendence/ft_transcendence/commit/cb683fc1993a799f5bbef7a462a3ceff9dd2d214)
- [[Refactor] 불필요한 코드 삭제](https://github.com/Last-transcendence/ft_transcendence/commit/2eb278ea8c97baa6b446ba97e150a068cfa891a9)
-
=> [HOTFIX] channel create 시 빈 채널 삭제

src/service/nextjs/src/component/common/accessControl/IsWithAuth.tsx, src/service/nextjs/src/pages/game/callback/index.tsx
- 로그인 되어있는 상태에서 토큰 삭제 시 401 에러 핸들
=> 로그인 되어있는 상태에서 토큰 삭제 시 401 에러 핸들

src/service/nextjs/src/component/main/matching-button/icon.tsx, src/service/nextjs/src/context/socket.context.tsx
- 아이콘-수정
- 채팅방 있어도 탁구채 아이콘 보이도록 수정
- 소켓이 없을때 보이던 loading 안보이도록
=> [Feat] [SCRUM-326] 아이콘-수정 #396

src/service/nextjs/src/component/common/creatOrModifyBody/CreatOrModifyBody.tsx, src/service/nextjs/src/component/profile/myProfile/FightDate.tsx
=> [Fix] Game history time zone 수정 #404

src/service/nextjs/src/component/auth/2fa/index.tsx
=> [Feat] [SCRUM-327] 2fa 에러메세지 개선 #407

src/service/nestjs/src/api/auth/auth.controller.ts, src/service/nestjs/src/api/channel/channel.gateway.ts, src/service/nestjs/src/api/channel/channel.service.ts, src/service/nestjs/src/api/game/game.controller.ts, src/service/nestjs/src/api/game/game.gateway.ts, src/service/nestjs/src/api/mute/mute.service.ts
=> [Debug] Add await to async services

src/service/nestjs/src/api/auth/auth.controller.ts, src/service/nestjs/src/api/game/game.gateway.ts, src/service/nestjs/src/common/multer/multer.config.ts, src/service/nextjs/src/component/common/creatOrModifyBody/CreatOrModifyBody.tsx, src/service/nextjs/src/component/common/monitorLogout/index.tsx, src/service/nextjs/src/component/game/scene/main/index.ts, src/service/nextjs/src/context/block.context.tsx, src/service/nextjs/src/context/game.context.tsx, src/service/nextjs/src/pages/auth/login/callback/index.tsx, src/service/nextjs/src/pages/game/callback/index.tsx
=> [Debug] router event on

src/service/nextjs/src/component/common/accessControl/IsWithAuth.tsx, src/service/nextjs/src/component/common/accessControl/IsWithNotAuth.tsx, src/service/nextjs/src/component/profile/myProfile/MyProfileMenu.tsx, src/service/nextjs/src/hook/useFetchData.ts, src/service/nextjs/src/pages/auth/logout/callback/index.tsx
=> [Feature] Logout callback page

src/service/nestjs/src/api/channel/channel.gateway.ts, src/service/nestjs/src/api/channel/channel.module.ts
- block 당한 user가 block한 유저를 게임 초대하지 못하도록 수정
-
-
=> [HOTFIX] block 당한 user가 block한 유저를 게임 초대하지 못하도록 수정

src/service/nextjs/src/component/common/monitorLogout/index.tsx
=> [HOTFIX] gameSocket build error

src/service/nestjs/src/api/game/game.gateway.ts
- gameHistory 보이지 않는 문제 해결
-
-
=> [HOTFIX] gameHistory 보이지 않는 문제 해결

src/service/nestjs/src/api/auth/service/auth.service.ts, src/service/nestjs/src/api/game/game.gateway.ts, src/service/nestjs/src/api/user/user.service.ts
=> [Feature] Validate duplicated email used in 2fa

src/service/nestjs/src/api/mute/mute.service.ts
=> [Fix] Mute time 1000 to 300000

src/service/nextjs/src/component/common/creatOrModifyBody/CreatOrModifyBody.tsx
-  회원가입 시 이메일 체크 메세지 출력 추가
- 이메일 중복, 이메일 미입력
=> 회원가입 시 이메일 체크 메세지 출력 추가

src/service/nestjs/src/api/block/block.controller.ts, src/service/nestjs/src/api/chatroom/chatroom.controller.ts, src/service/nestjs/src/api/chatroom/chatroom.module.ts
=> [Fix] Return chatrooms without blocked user

src/service/nestjs/src/api/auth/service/auth.service.ts
=> [Fix] register service

src/service/nestjs/src/api/user/user.controller.ts
=> [Fix] User update

src/service/nestjs/src/api/chatroom/chatroom.controller.ts, src/service/nextjs/src/component/common/accessControl/IsWithAuth.tsx, src/service/nextjs/src/component/common/monitorLogout/index.tsx
=> [Fix] User status

src/service/nestjs/src/api/chatroom/chatroom.controller.ts, src/service/nextjs/src/component/common/accessControl/IsWithAuth.tsx
=> [Fix] User status, Return chatroom without blocked users

src/service/nestjs/src/api/user/user.controller.ts
=> [Fix] User controller update

src/service/nestjs/src/api/user/user.service.ts
=> [Fix] user.service.ts

src/service/nestjs/src/api/user/user.controller.ts
=> [Fix] User controller

src/service/nestjs/src/api/user/user.controller.ts, src/service/nextjs/src/component/common/accessControl/IsWithAuth.tsx, src/service/nextjs/src/component/common/monitorLogout/index.tsx
=> [Fix] useEffect dependency array

src/service/nextjs/src/component/common/monitorLogout/index.tsx
=> [Fix] remove setMe(null)

src/service/nestjs/src/api/user/user.controller.ts, src/service/nextjs/src/component/profile/myProfile/MyProfileBody.tsx
=> [Fix] Game history
